producer:
  container:
    image: kafka-producer
    portPod: 8080 #порт поды
    portIn: 8080 #порт сервиса внутри поды
  replicaCount: 1

consumer:
  container:
    image: kafka-consumer
    portPod: 8090 
    portIn: 8090 
  replicaCount: 1

ingress:
  host: localhost
  producer:
    path: /post
  consumer:
    path: /get