producer:
  container:
    image: kafka-producer
    portPod: 8080 #порт поды
    portIn: 8080 #порт сервиса внутри поды
  replicaCount: 1

consumer:
  container:
    image: kafka-consumer
    portPod: 8090 
    portIn: 8090 
  replicaCount: 1

kafka:
  container:
    image: confluentinc/cp-kafka
    IpExternal: 192.168.1.74
  replicaCount: 1 #только 1; для multi-node Kafka кластера нужен StatefulSet манифест а не Deployment (в prodaction StatefulSet)

ingress:
  host: localhost
  producer:
    path: /post
  consumer:
    path: /get