apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kafka
  labels:
    app: {{ .Release.Name }}-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kafka
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kafka
    spec:
      containers:
      - name: {{ .Release.Name }}-kafka
        image: {{ .Values.kafka.container.image }}
        ports:
        - containerPort: 9092
          name: internal
        - containerPort: 9093
          name: controller
        - containerPort: 9094
          name: external
        env:
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_NODE_ID
          value: "1"
        - name: CLUSTER_ID
          value: "Mk3C1PVATnK2kf7dLr00Vg"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@127.0.0.1:9093"
        - name: KAFKA_LISTENERS
          value: "INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://kafka:9092,EXTERNAL://{{ .Values.kafka.container.IpExternal }}:9094"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        - name: KAFKA_CLUSTER_ID
          value: "Mk3C1PVATnK2kf7dLr00Vg"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "false"
        - name: KAFKA_FORMAT_STORAGE
          value: "true"
        readinessProbe:
          tcpSocket:
            port: internal
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: internal
          initialDelaySeconds: 30
          periodSeconds: 20