apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka-service
  labels:
    app: {{ .Release.Name }}-kafka
spec:
  selector:
    app: {{ .Release.Name }}-kafka
  ports:
  - name: internal
    port: 9092
    targetPort: 9092
    protocol: TCP
  - name: external
    port: 9094
    targetPort: 9094
    protocol: TCP
  type: NodePort