apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app: {{ .Release.Name }}-server
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.producer.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-producer-service
            port:
              number: {{ .Values.producer.container.portPod }}

      - path: {{ .Values.ingress.consumer.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-consumer-service
            port:
              number: {{ .Values.consumer.container.portPod }}